name: Publish to registry, test and deploy app

on:
  push

jobs:
  frontend_test:
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 8
        uses: actions/setup-node@v1
        with:
          node-version: 12.0
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: ls
        run: ls && echo ${{ steps.yarn-cache.outputs.dir }}
      - name: Yarn install
        run: yarn install
