name: Publish to registry, test and deploy app

on:
  push

jobs:
  frontend_test:
    runs-on: [ubuntu-18.04]
    container: node:12.0-alpine
    steps:
      - uses: actions/checkout@v1
      - name: Get yarn cache
        working-directory: ./src/frontend
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          working-directory: ./src/frontend
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn1-
      - name: ls
        working-directory: ./src/frontend
        run: ls && echo ${{ steps.yarn-cache.outputs.dir }}
      - name: Yarn install
        working-directory: ./src/frontend
        run: yarn install
